FROM pgvector/pgvector:pg16

RUN apt-get update \
    && apt-get install -y \
        build-essential \
        postgresql-server-dev-16 \
        curl \
    && curl -L https://github.com/pgbigm/pg_bigm/archive/refs/tags/v1.2-20240606.tar.gz | tar xz \
    && cd pg_bigm-1.2-20240606 \
    && make USE_PGXS=1 \
    && make USE_PGXS=1 install \
    && cd .. \
    && rm -rf pg_bigm-1.2-20240606 \
    && apt-get remove -y build-essential postgresql-server-dev-16 curl \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
