spring:
  application:
    name: ahaive

#  profiles:
#    active: dev

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight([%-3level]) %cyan(%logger{5}) - %msg%n"

resilience4j:
  circuitbreaker:
    instances:
      ai-client:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3